apiVersion: v1
kind: ServiceAccount
metadata:
  name: webterminal
  namespace: webterminal
  labels:
    app: webterminal
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: webterminal
  labels:
    app: webterminal
subjects:
  - kind: ServiceAccount
    namespace: webterminal
    name: webterminal
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io