---
apiVersion: v1
kind: Service
metadata:
  name: webterminal-<user>
  namespace: webterminal
  labels:
    app: webterminal-<user>
    target: webterminal-<user>
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: http
  selector:
    app: webterminal-<user>
    target: webterminal-<user>
